package main

var quotes = []string{
	"No one cares about your excuses. Millionaires care about results.",
	"Comfort is the enemy of success.",
	"You’re broke because you waste time, not money.",
	"Discipline makes men rich. Distraction makes men broke.",
	"If you don't sacrifice for your dream, your dream becomes the sacrifice.",
	"The world doesn’t owe you a thing. Earn it.",
	"Men who chase women rarely catch wealth.",
	"If you're not building, you're being used as a tool by someone who is.",
	"Money doesn’t respect laziness.",
	"You can’t be a king hanging with jesters.",
	"Every dollar you spend on impressing others is a dollar stolen from your future.",
	"Your 9–5 won't make you rich. Your 6–12 might.",
	"You’ll never win by playing it safe.",
	"Your last bad decision is why you're not ahead.",
	"Sleep like the poor, live like the poor.",
	"Wealthy men read. Weak men scroll.",
	"No mentor will save a lazy student.",
	"You don’t deserve luxury if you haven’t earned pain.",
	"You’re not stuck, you’re comfortable.",
	"The grind doesn’t care how you feel.",
	"Broke men talk. Rich men execute.",
	"Fear keeps men broke.",
	"Your habits today are your bank account tomorrow.",
	"Hard truth: No one will build your dream but you.",
	"Losers want motivation. Winners build discipline.",
	"You can't build an empire with a peasant's mindset.",
	"The gym and the grind are where men are forged.",
	"Chasing women costs money. Chasing money attracts women.",
	"Your future depends on what you do after 6 PM.",
	"Stop blaming your parents. Start acting like a man.",
	"If you think like everyone else, you’ll earn like everyone else.",
	"Your success is your responsibility. No one else's.",
	"If it doesn’t scare you, it won’t change you.",
	"You’re not tired, you’re unmotivated.",
	"They laughed at you? Good. Keep building.",
	"A man without purpose is a weapon without a target.",
	"Respect is earned, not requested.",
	"The broke man blames. The rich man adapts.",
	"Every missed day is another man’s advantage.",
	"The mirror doesn't lie. You do.",
	"You’re not too late. You’re just too slow.",
	"Success isn’t found, it’s forged.",
	"They sleep. You build.",
	"Men who avoid discomfort stay mediocre.",
	"No one’s coming to save you. Be your own hero.",
	"Luxury is rented by pain and consistency.",
	"If you’re not learning, you’re losing.",
	"Most men die in regret. Don’t be most men.",
	"You have time. You just waste it.",
	"Hard work beats talent when talent gets lazy.",
	"Success is earned in silence, not posted online.",
}
